name: Cross-Platform CI with Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Áp dụng chiến lược Matrix
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Sử dụng biến os từ matrix
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B clean package

      - name: Upload JAR artifact
        if: matrix.os == 'ubuntu-latest' # Chỉ upload từ một môi trường để tránh trùng lặp
        uses: actions/upload-artifact@v4
        with:
          name: BTVN_WEEK9-artifact
          path: target/*.jar